name: Laravel CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: php artisan test

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2
        with:
          server_ip: ${{ secrets.SERVER_IP }}
          server_port: ${{ secrets.SERVER_PORT }}
          server_user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'public/'
          target: '/path/to/deploy'
